import type { AggregateDef, DomainModel, Region } from '../../ast/domain.js';
import type { ContextMapModel } from '../../ast/contextmap.js';
import { machineToMermaid } from './statechart.js';
import { domainToMermaid } from './domainDiagram.js';
import { contextMapToMermaid } from './contextMap.js';

export interface GeneratedFile { relPath: string; content: string }

export const MD_HEADER = '<!-- generated by lattice; do not edit -->';
export const MMD_HEADER = '%% generated by lattice; do not edit';

const mermaidBlock = (src: string): string => '```mermaid\n' + src + '```';

/** Assembles the per-spec diagram projections (design §6): `spec.diagrams.md` — a human-readable
 *  page embedding every diagram inline — plus one standalone `.mmd` per diagram under `diagrams/`
 *  (renderable on its own, e.g. by tooling that only reads `.mmd` files). Generates what's
 *  modeled (spec §11): an aggregate with no `machine` contributes no statechart section/file. */
export function specDiagramFiles(m: DomainModel): GeneratedFile[] {
  const md: string[] = [MD_HEADER, '', `# ${m.context} — diagrams`, ''];
  if (m.doc) md.push(`*${m.doc}*`, '');

  md.push('## Domain', '', mermaidBlock(domainToMermaid(m)));

  const files: GeneratedFile[] = [];
  const regionsOf = (a: AggregateDef): Region[] => a.machine?.regions ?? [];

  for (const a of m.aggregates) {
    for (const r of regionsOf(a)) {
      md.push('', `## ${a.name} — ${r.name}`, '');
      if (a.doc) md.push(a.doc, '');
      md.push(mermaidBlock(machineToMermaid(a, r)));
    }
  }

  files.push({ relPath: 'spec.diagrams.md', content: md.join('\n') + '\n' });
  files.push({ relPath: `diagrams/CD_${m.context}.mmd`, content: MMD_HEADER + '\n' + domainToMermaid(m) });

  for (const a of m.aggregates) {
    for (const r of regionsOf(a)) {
      files.push({ relPath: `diagrams/SD_${a.name}_${r.name}.mmd`, content: MMD_HEADER + '\n' + machineToMermaid(a, r) });
    }
  }

  return files;
}

/** Assembles the workspace-level context-map projection (design §6): `context-map.generated.md`
 *  embeds the flowchart plus a `## Relationships` bullet list, and `diagrams/context-map.mmd`
 *  carries the standalone diagram source. */
export function workspaceDiagramFiles(map: ContextMapModel): GeneratedFile[] {
  const md: string[] = [MD_HEADER, '', `# ${map.name} — context map`, ''];
  if (map.doc) md.push(`*${map.doc}*`, '');

  md.push(mermaidBlock(contextMapToMermaid(map)));

  md.push('', '## Relationships', '');
  for (const r of map.relationships) {
    md.push(`- ${r.left} ${r.kind} ${r.right}`);
    if (r.doc) md.push(`  ${r.doc}`);
  }

  return [
    { relPath: 'context-map.generated.md', content: md.join('\n') + '\n' },
    { relPath: 'diagrams/context-map.mmd', content: MMD_HEADER + '\n' + contextMapToMermaid(map) }
  ];
}
