import type { AggregateDef, DomainModel, Field, TypeRef } from '../ast/domain.js';

// Field-type → TS type for the spec-state contract. Unlike generate/render/types.ts (which only
// needs a foreign-id `string` for enums), the contract must expose the literal value union so
// SpecOverrides functions are checked against the real enum domain.
function tsType(model: DomainModel, t: TypeRef): string {
  switch (t.kind) {
    case 'prim':
      return t.prim === 'Text' || t.prim === 'Id' ? 'string' : 'number'; // Int/Money/Date/Duration → number
    case 'enum': {
      const en = model.enums.find(e => e.name === t.enum);
      if (!en) throw new Error(`unknown enum ${t.enum}`);
      return en.values.map(v => `'${v}'`).join(' | ');
    }
    case 'ref':
      return 'string | null'; // foreign id
    case 'list':
      return `${tsType(model, t.of)}[]`;
    case 'value':
      throw new Error(`unsupported field type kind: value (${t.value}) — the conform contract renderer does not yet support value-type fields`);
  }
}

function fieldLine(model: DomainModel, f: Field): string {
  return `  ${f.name}: ${tsType(model, f.type)};`;
}

function aggregateInterface(model: DomainModel, a: AggregateDef): string {
  const lines = a.fields.map(f => fieldLine(model, f));
  for (const r of a.machine?.regions ?? []) {
    lines.push(`  ${r.name}: ${r.states.map(s => `'${s.name}'`).join(' | ')};`);
  }
  return `export interface ${a.name}SpecState {\n${lines.join('\n')}\n}`;
}

export function renderContract(model: DomainModel): string {
  const aggs = model.aggregates.map(a => aggregateInterface(model, a));
  const overrideMembers = model.aggregates.map(a =>
    `  ${a.name}?: { [K in keyof ${a.name}SpecState]?: (db: unknown, row: Record<string, unknown>) => ${a.name}SpecState[K] };`);

  const transitionMembers = model.aggregates
    .flatMap(a => (a.machine?.transitions ?? []).map(t => ({ t, a })))
    .map(({ t, a }) => `    ${t.name}(db: unknown, row: ${a.name}SpecState, gen: DriveGen): void;`);
  const specStateUnion = model.aggregates.map(a => `${a.name}SpecState`).join(' | ');
  const createMembers = model.aggregates.map(a =>
    `    ${a.name}?(db: unknown, id: string, gen: DriveGen): void;`);

  return [
    `// GENERATED by lattice conform --contract from context ${model.context} — DO NOT EDIT.`,
    `// Regenerating the spec regenerates this file; stale overrides then FAIL TO COMPILE (design §4.2).`,
    '',
    ...aggs,
    '',
    `export interface SpecOverrides {`,
    ...overrideMembers,
    `}`,
    '',
    `export function defineOverrides(o: SpecOverrides): SpecOverrides { return o }`,
    '',
    `export interface DriveGen { int(min: number, max: number): number; id(): string; pick<T>(xs: T[]): T; clock(): number }`,
    `export type DriveOutcome = { accepted: true } | { accepted: false; rejected: string };`,
    `export interface SpecDrivers {`,
    `  transitions: {`,
    ...transitionMembers,
    `  };`,
    `  superset?: Record<string, (db: unknown, row: ${specStateUnion}, gen: DriveGen) => void>;`,
    `  create: {`,
    ...createMembers,
    `  };`,
    `}`,
    '',
    `export function defineDrivers(d: SpecDrivers): SpecDrivers { return d }`,
    '',
  ].join('\n');
}
