import type { GenPlan, PlanInvariant } from '../plan.js';
import { compileInvariantCheck } from '../invariantCheck.js';
import { checkFnName } from './commands.js';

// Provenance comment wording (human-decided, see task-7 brief): cite the per-invariant `adopted`
// provenance (accurate per-invariant) and, separately, the judged witnesses as "exercising
// aggregate <Name>" — NOT as having "judged this invariant". witnessIds are aggregate-scoped (the
// ledger has no field identifying which invariant a verdict judged), so claiming a witness judged
// this specific invariant would be an overclaim.
function provenanceComment(inv: PlanInvariant): string {
  const provenance = inv.anchors.provenance.length ? inv.anchors.provenance.join(', ') : 'none';
  let comment = `// spec: invariant ${inv.name}  [provenance: ${provenance}`;
  if (inv.anchors.witnessIds.length > 0) {
    comment += `; judged witnesses exercising aggregate ${inv.aggregate}: ${inv.anchors.witnessIds.join(', ')}`;
  }
  comment += ']';
  return comment;
}

function renderCheck(inv: PlanInvariant): string {
  const compiled = compileInvariantCheck(inv);
  // Params are typed `any`, not the aggregate's own row interface: row-kind checks may receive a
  // ref-flattened row (see render/commands.ts renderFlattenHelper, which returns `any` — nested ref
  // fields like `row.latestInvoice.amountPaid` aren't part of the aggregate's own shape), and
  // table-kind checks iterate `rows` from a raw `db...all()` query result. `any` here matches the
  // looseness already established at that boundary rather than fighting it.
  const param = compiled.kind === 'row' ? 'row: any' : 'rows: any[]';
  return (
    `${provenanceComment(inv)}\n` +
    `export function ${checkFnName(inv.name)}(${param}): boolean {\n` +
    `  return (${compiled.bodyTs});\n` +
    `}\n`
  );
}

export function renderInvariants(plan: GenPlan): string {
  const header = `// GENERATED by lattice from context ${plan.context} — DO NOT EDIT. Regenerate instead.\n\n`;
  const checks = plan.aggregates.flatMap(a => a.invariants).map(renderCheck);
  return header + checks.join('\n');
}
