import type { GenPlan } from '../plan.js';

// Package-scaffold files for the generated service: a standalone package with its own tsc+vitest
// gates (design §3 — "own package.json", "own tsc+vitest gates", clean-dir regen). Static-but-
// parameterized: only the package name varies with the spec's context; everything else is fixed
// scaffold, so output stays byte-identical across regenerations of the same spec.

function packageJson(plan: GenPlan): string {
  const pkg = {
    name: `@lattice/generated-${plan.context.toLowerCase()}`,
    private: true,
    type: 'module',
    scripts: { test: 'vitest run', typecheck: 'tsc --noEmit' },
    dependencies: {
      'better-sqlite3': '^12.11.1',
    },
    devDependencies: {
      '@types/better-sqlite3': '^7.6.13',
      '@types/node': '^22.0.0',
      typescript: '^5.6.0',
      vitest: '^2.1.0',
    },
  };
  return JSON.stringify(pkg, null, 2) + '\n';
}

const TSCONFIG = JSON.stringify({
  compilerOptions: {
    target: 'ES2022', module: 'NodeNext', moduleResolution: 'NodeNext',
    strict: true, noUncheckedIndexedAccess: true, skipLibCheck: true,
    outDir: 'dist', rootDir: '.',
  },
  include: ['*.ts'],
}, null, 2) + '\n';

const VITEST_CONFIG =
  `import { defineConfig } from 'vitest/config';\n` +
  `export default defineConfig({ test: { include: ['*.test.ts'], passWithNoTests: true } });\n`;

// Regen is a clean-dir rewrite of generator artifacts only (see generate.ts). npm/install
// output and the demo's on-disk DB are not generator artifacts, so they must be gitignored —
// otherwise a plain `generate` run deletes a committed lock file and the empty-diff guarantee
// (design §3) breaks.
const GITIGNORE =
  `node_modules/\n` +
  `package-lock.json\n` +
  `demo.db\n`;

const DB_TS =
  `// GENERATED by lattice — DO NOT EDIT. Regenerate instead.\n\n` +
  `import Database from 'better-sqlite3';\n` +
  `import { readFileSync } from 'node:fs';\n` +
  `import { fileURLToPath } from 'node:url';\n` +
  `import { dirname, join } from 'node:path';\n\n` +
  `const here = dirname(fileURLToPath(import.meta.url));\n\n` +
  `// Opens a better-sqlite3 database at \`path\` (default ':memory:') and applies the generated\n` +
  `// schema.sql. Callers needing a persistent DB pass a file path.\n` +
  `export function openDb(path: string = ':memory:'): Database.Database {\n` +
  `  const db = new Database(path);\n` +
  `  db.exec(readFileSync(join(here, 'schema.sql'), 'utf8'));\n` +
  `  return db;\n` +
  `}\n`;

export function renderPackageFiles(plan: GenPlan): Record<string, string> {
  return {
    'package.json': packageJson(plan),
    'tsconfig.json': TSCONFIG,
    'vitest.config.ts': VITEST_CONFIG,
    'db.ts': DB_TS,
    '.gitignore': GITIGNORE,
  };
}
