import type { GenPlan, PlanAggregate } from '../plan.js';
import type { Field } from '../../ast/domain.js';
import { qid } from './sql.js';

// The Account row's own-column names, in DDL/type order: fields, then region-state columns.
function columns(a: PlanAggregate): string[] {
  return [...a.fields.map((f: Field) => f.name), ...a.regions.map(r => r.name)];
}

function keyField(a: PlanAggregate): string {
  const key = a.fields.find((f: Field) => f.key);
  if (!key) throw new Error(`aggregate ${a.name} has no key field — repo renderer requires exactly one`);
  return key.name;
}

function aggregateRepo(a: PlanAggregate): string {
  const key = keyField(a);
  const cols = columns(a);
  const insertCols = cols.map(qid).join(', ');
  const insertParams = cols.map(c => `@${c}`).join(', ');
  const updateSet = cols.filter(c => c !== key).map(c => `${qid(c)}=@${c}`).join(', ');
  return (
    `// spec: aggregate ${a.name}\n` +
    `export function get${a.name}(db: Database.Database, id: string): ${a.name} | undefined {\n` +
    `  return db.prepare('SELECT * FROM ${qid(a.name)} WHERE ${qid(key)} = ?').get(id) as ${a.name} | undefined;\n` +
    `}\n` +
    `export function insert${a.name}(db: Database.Database, row: ${a.name}): void {\n` +
    `  db.prepare('INSERT INTO ${qid(a.name)} (${insertCols}) VALUES (${insertParams})').run(row);\n` +
    `}\n` +
    `export function update${a.name}(db: Database.Database, row: ${a.name}): void {\n` +
    `  db.prepare('UPDATE ${qid(a.name)} SET ${updateSet} WHERE ${qid(key)}=@${key}').run(row);\n` +
    `}\n`
  );
}

const APPEND_OUTBOX =
  `export function appendOutbox(db: Database.Database, eventType: string, aggregateId: string, payload: object): void {\n` +
  `  db.prepare('INSERT INTO outbox (event_type, aggregate_id, payload) VALUES (?,?,?)')\n` +
  `    .run(eventType, aggregateId, JSON.stringify(payload));\n` +
  `}\n`;

export function renderRepo(plan: GenPlan): string {
  const header =
    `// GENERATED by lattice from context ${plan.context} — DO NOT EDIT. Regenerate instead.\n\n` +
    `import type Database from 'better-sqlite3';\n` +
    `import type { ${plan.aggregates.map(a => a.name).join(', ')} } from './types.js';\n\n`;
  const aggs = plan.aggregates.map(aggregateRepo).join('\n');
  return header + aggs + '\n' + APPEND_OUTBOX;
}
