import type { GenPlan, PlanAggregate } from '../plan.js';
import type { Field, TypeRef } from '../../ast/domain.js';

const sqlType = (t: TypeRef): 'TEXT' | 'INTEGER' =>
  (t.kind === 'prim' && (t.prim === 'Text' || t.prim === 'Id')) || t.kind === 'ref' || t.kind === 'enum' ? 'TEXT' : 'INTEGER';

export const OUTBOX_DDL =
  `CREATE TABLE outbox (\n` +
  `  seq INTEGER PRIMARY KEY AUTOINCREMENT,\n` +
  `  event_type TEXT NOT NULL,\n` +
  `  aggregate_id TEXT NOT NULL,\n` +
  `  payload TEXT NOT NULL\n);\n`;

function tableDdl(a: PlanAggregate): string {
  const cols = a.fields.map((f: Field) => `  ${f.name} ${sqlType(f.type)}${f.key ? ' PRIMARY KEY' : ''}`);
  for (const r of a.regions) cols.push(`  ${r.name} TEXT NOT NULL`);
  return `-- spec: aggregate ${a.name}\nCREATE TABLE ${a.name} (\n${cols.join(',\n')}\n);\n`;
}

export function renderDdl(plan: GenPlan): string {
  return `-- GENERATED by lattice — DO NOT EDIT.\n\n` +
    plan.aggregates.map(tableDdl).join('\n') + '\n' + OUTBOX_DDL;
}
