import { describe, it, expect } from 'vitest';
import { renderTsTypes } from './ts-types.js';
import { loadLatText } from '../../parse/fromLangium.js';
import type { DomainModel } from '../../ast/domain.js';

// Slice 3: the faithful full-model TS emitter. Fixture is built through the real parser (loadLatText)
// so head-Optional normalization (→ `?`), carrier resolution, and union flattening are all exercised
// exactly as production input arrives. Assertions are on rendered strings (the output is a faithful
// type SURFACE — it references external generic/carrier types and is not run through tsc).

const SPEC = `context Rich {
  builtin Metadata
  builtin Currency
  enum Mode { fast, slow }
  value Amount {
    amount   : Money
    currency : Currency
  }
  entity DraftWithBill { draftId : Id key }
  entity DraftWithInvoice { draftId : Id key }
  aggregate Ledger {
    ledgerId : Id key
    owner    : ref DraftWithBill const
    meta     : Metadata
    mode     : Mode
    approved : Optional<Money>
    balances : Map<Id, Amount>
    settle   : Result<Amount, Metadata>
    holds    : Map<Id, Optional<Money>>
    lifecycle access {
      states { trialing @initial, active @active, ended @terminal }
      transition go { from trialing to active }
    }
  }
  event kicked { reason : Text }
}
`;

function render(spec: string): string {
  const r = loadLatText(spec);
  if (!r.ok) throw new Error(`load failed: ${JSON.stringify(r.diagnostics)}`);
  return renderTsTypes(r.model);
}

describe('renderTsTypes — faithful per-kind output', () => {
  const ts = render(SPEC);

  it('emits a header naming the context', () => {
    expect(ts).toContain('// GENERATED by lattice from context Rich — DO NOT EDIT. Regenerate instead.');
  });

  it('emits an alias block for declared builtin carriers', () => {
    expect(ts).toContain('export type Metadata = unknown;');
    expect(ts).toContain('export type Currency = unknown;');
  });

  it('emits enums as string-literal unions', () => {
    expect(ts).toContain("export type Mode = 'fast' | 'slow';");
  });

  it('emits a value interface with prim (Money→number) and carrier sub-fields', () => {
    expect(ts).toContain('export interface Amount {\n  amount: number;\n  currency: Currency;\n}');
  });

  it('renders a key/const field as readonly, Id→string', () => {
    expect(ts).toContain('  ledgerId: string;');
    expect(ts).toContain('  readonly owner: string;');   // ref → foreign id string; const → readonly
  });

  it('renders a carrier field by its bare name and an enum field by its alias', () => {
    expect(ts).toContain('  meta: Metadata;');
    expect(ts).toContain('  mode: Mode;');
  });

  it('renders a head Optional<Money> as an optional property (not `| null`)', () => {
    expect(ts).toContain('  approved?: number;');
    expect(ts).not.toContain('approved: number | null');
  });

  it('renders Map<K,V> as Record and a nested Optional as `| null`', () => {
    expect(ts).toContain('  balances: Record<string, Amount>;');
    expect(ts).toContain('  holds: Record<string, number | null>;');
  });

  it('renders a generic ctor faithfully with resolved args', () => {
    expect(ts).toContain('  settle: Result<Amount, Metadata>;');
  });

  it('renders a machine region as a state-literal union member', () => {
    expect(ts).toContain("  access: 'trialing' | 'active' | 'ended';");
  });

  it('emits an event interface', () => {
    expect(ts).toContain('export interface kicked {\n  reason: string;\n}');
  });
});

describe('renderTsTypes — unions, nested children, exhaustiveness, determinism', () => {
  it('renders a union of arms joined by `|`', () => {
    const ts = render(`context C {
  builtin A builtin B
  aggregate G { gId : Id key  pick : A | B }
}`);
    expect(ts).toContain('  pick: A | B;');
  });

  it('emits a nested aggregate-owned child as its own interface', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    lines     : List<InvoiceLine>
    entity InvoiceLine { lineId : Id key  amount : Money }
  }
}`);
    expect(ts).toContain('export interface InvoiceLine {\n  lineId: string;\n  amount: number;\n}');
    expect(ts).toContain('  lines: InvoiceLine[];');   // owned collection → T[]
  });

  it('distinguishes an owned collection (embed child) from a foreign ref list (id strings)', () => {
    // `plans: List<ref Plan>` where Plan is TOP-LEVEL is NOT an owned collection — its elements are
    // foreign ids, so it renders `string[]`, unlike the owned `lines: InvoiceLine[]` above.
    const ts = render(`context C {
  entity Plan { planId : Id key }
  aggregate Cart {
    cartId : Id key
    plans  : List<ref Plan>
  }
}`);
    expect(ts).toContain('  plans: string[];');
    expect(ts).not.toContain('plans: Plan[]');
  });

  it('never throws on any TypeRef kind (all ten present)', () => {
    // prim, enum, ref, value, list, optional, map, generic, union, carrier
    const ts = render(`context All {
  builtin Blob
  enum E { a, b }
  value V { n : Money }
  entity Ent { entId : Id key }
  aggregate Agg {
    aggId : Id key
    p     : Int
    e     : E
    r     : ref Ent
    v     : V
    l     : List<Int>
    o     : Optional<Money>
    m     : Map<Id, Int>
    g     : Wrapper<Int>
    u     : E | V
    c     : Blob
  }
}`);
    expect(ts).toContain('export interface Agg {');
    expect(ts).toContain('  g: Wrapper<number>;');
    expect(ts).toContain('  o?: number;');
    expect(ts).toContain('  c: Blob;');
  });

  it('is deterministic (pure)', () => {
    const r = loadLatText(SPEC);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    const a = renderTsTypes(r.model);
    const clone = JSON.parse(JSON.stringify(r.model)) as DomainModel;
    expect(renderTsTypes(clone)).toBe(a);
  });
});

describe('renderTsTypes — field-level docs and visibility tags', () => {
  it('emits /** <doc> @public */ above a documented @public field', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    /// The total amount due on this invoice.
    totalDue  : Money @public
  }
}`);
    expect(ts).toContain('  /** The total amount due on this invoice. @public */');
    expect(ts).toContain('  totalDue: number;');
    // JSDoc line immediately precedes the field line
    expect(ts).toContain('  /** The total amount due on this invoice. @public */\n  totalDue: number;');
  });

  it('emits /** <doc> @public (hook-only) */ for a @hookOnly field', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    /// Fee visible to hooks only.
    hookFee   : Money @hookOnly
  }
}`);
    expect(ts).toContain('  /** Fee visible to hooks only. @public (hook-only) */');
    expect(ts).toContain('  /** Fee visible to hooks only. @public (hook-only) */\n  hookFee: number;');
  });

  it('emits /** <doc> @public (hook-only) */ when both @public and @hookOnly are present', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    /// Both flags set.
    both : Money @public @hookOnly
  }
}`);
    expect(ts).toContain('  /** Both flags set. @public (hook-only) */');
  });

  it('emits just /** <doc> */ for an internal field with a doc but no visibility tag', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    /// Internal notes field.
    notes : Text
  }
}`);
    expect(ts).toContain('  /** Internal notes field. */');
    expect(ts).toContain('  /** Internal notes field. */\n  notes: string;');
  });

  it('emits no JSDoc for an undocumented field without visibility tags', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    amount    : Money
  }
}`);
    expect(ts).not.toContain('/**');
    expect(ts).toContain('  amount: number;');
  });

  it('emits /** @public */ (no doc) for a @public field with no doc comment', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    amount    : Money @public
  }
}`);
    expect(ts).toContain('  /** @public */');
    expect(ts).toContain('  /** @public */\n  amount: number;');
  });
});

describe('renderTsTypes — enum-level JSDoc (Slice 8)', () => {
  it('emits /** <doc> */ above a documented plain enum', () => {
    const ts = render(`context C {
  /// The billing period.
  enum Period { monthly, annual }
  entity E { eId : Id key  p : Period }
}`);
    expect(ts).toContain("/** The billing period. */\nexport type Period = 'monthly' | 'annual';");
  });

  it('emits /** <doc> */ above a documented sum-type enum', () => {
    const ts = render(`context C {
  builtin Amount
  /// A grant amount variant.
  enum Grant { monetary(Amount), none }
  entity E { eId : Id key  g : Grant }
}`);
    expect(ts).toContain("/** A grant amount variant. */\nexport type Grant =");
  });

  it('emits no JSDoc for an undocumented enum', () => {
    const ts = render(`context C {
  enum Mode { fast, slow }
  entity E { eId : Id key  m : Mode }
}`);
    expect(ts).not.toContain('/**');
    expect(ts).toContain("export type Mode = 'fast' | 'slow';");
  });
});

describe('renderTsTypes — module grouping banners (Slice 6)', () => {
  it('emits // ── module: <name> ── before a module\'s interfaces', () => {
    const ts = render(`context Billing {
  enum TopLevel { a, b }

  module BillingEngine {
    value Amount {
      amount : Money
    }
    aggregate Invoice {
      invoiceId : Id key
      total     : Money @unsigned
    }
  }

  module ItemTimelines {
    entity LineItem {
      lineId : Id key
    }
  }
}`);
    // Banner for each module
    expect(ts).toContain('// ── module: BillingEngine ──');
    expect(ts).toContain('// ── module: ItemTimelines ──');

    // Module's interfaces appear after their banner
    const engineBannerIdx = ts.indexOf('// ── module: BillingEngine ──');
    const itemBannerIdx = ts.indexOf('// ── module: ItemTimelines ──');
    const amountIdx = ts.indexOf('export interface Amount');
    const invoiceIdx = ts.indexOf('export interface Invoice');
    const lineItemIdx = ts.indexOf('export interface LineItem');

    expect(engineBannerIdx).toBeGreaterThanOrEqual(0);
    expect(itemBannerIdx).toBeGreaterThanOrEqual(0);
    expect(amountIdx).toBeGreaterThan(engineBannerIdx);
    expect(invoiceIdx).toBeGreaterThan(engineBannerIdx);
    expect(lineItemIdx).toBeGreaterThan(itemBannerIdx);

    // Top-level enum appears BEFORE any module banner
    const topLevelIdx = ts.indexOf("export type TopLevel = 'a' | 'b';");
    expect(topLevelIdx).toBeGreaterThanOrEqual(0);
    expect(topLevelIdx).toBeLessThan(engineBannerIdx);
  });

  it('model without modules emits no banner lines', () => {
    const ts = render(`context Plain {
  entity Thing { thingId : Id key }
}`);
    expect(ts).not.toContain('// ── module:');
  });
});
