import type { AggregateDef, DomainModel, EntityDef, EventDef, Field, TypeRef, ValueDef } from '../../ast/domain.js';
import { ownedCollectionChild } from '../../ast/domain.js';

// Faithful full-model TypeScript type emitter (Slice 3). Renders the ENTIRE DomainModel — enums,
// values, entities, aggregates (+ nested children), events, and `builtin` carriers — with the full
// CML rich type system. This is the "replace CML" codegen artifact, NOT the solver-scoped SQLite
// reference service (render/types.ts): that one is GenPlan-bound and throws on value/list/carried
// kinds; this one renders from the DomainModel directly and NEVER throws on any TypeRef kind.
//
// The emitted file is a faithful type SURFACE: it may reference external generic constructors
// (`Result<…>`) and opaque `builtin` carriers that this file does not itself define, exactly as CML
// output references shared type libraries. It is not intended to typecheck standalone under `tsc`.

/** Every TypeRef kind → its TS type. Exhaustive by design (no `default`) so tsc flags a new kind. */
function tsType(t: TypeRef): string {
  switch (t.kind) {
    case 'prim': return t.prim === 'Text' || t.prim === 'Id' ? 'string' : t.prim === 'Boolean' ? 'boolean' : 'number'; // Int/Money/Date/Duration → number (ticks)
    case 'enum': return t.enum;            // the emitted string-literal-union alias
    case 'ref': return 'string';           // foreign id (incl. qualified cross-context refs)
    case 'value': return t.value;          // the emitted value interface
    case 'list': return `${tsType(t.of)}[]`;
    case 'optional': return `${tsType(t.of)} | null`;                       // nested optional (head Optional is the `?` flag)
    case 'map': return `Record<${tsType(t.key)}, ${tsType(t.of)}>`;          // Map<K,V>
    case 'generic': return `${t.ctor}<${t.args.map(tsType).join(', ')}>`;    // Result<T,E>, user generics — faithful, external
    case 'union': return t.arms.map(tsType).join(' | ');                     // A | B
    case 'carrier': return t.name;         // opaque builtin — resolved by the top-of-file alias block
  }
}

// A field renders as an optional PROPERTY (`name?: T`) when the head is optional — the parser
// normalizes a head `Optional<T>` to Field.optional, so that flag is the single source of truth for
// head-optionality (a nested optional stays a `| null` union via tsType). `const` → `readonly`,
// matching render/types.ts. `typeStr` overrides the field's own type (used for owned collections,
// which embed the child interface rather than exposing meaningless foreign ids).
function fieldLine(f: Field, typeStr = tsType(f.type)): string {
  return `  ${f.const ? 'readonly ' : ''}${f.name}${f.optional ? '?' : ''}: ${typeStr};`;
}

function iface(name: string, fields: Field[], extra: string[] = []): string {
  const lines = [...fields.map(f => fieldLine(f)), ...extra];
  return `export interface ${name} {\n${lines.join('\n')}\n}\n`;
}

function valueIface(v: ValueDef): string { return iface(v.name, v.fields); }
function entityIface(e: EntityDef): string { return iface(e.name, e.fields); }
function eventIface(e: EventDef): string { return iface(e.name, e.fields); }

function aggregateIface(a: AggregateDef): string {
  // An owned collection (`List<ref Child>` over a nested entity) embeds the child interface —
  // `lines: InvoiceLine[]` — NOT `string[]`: an owned child has no identity outside its owner, so
  // the foreign-id rendering that a plain `ref` gets would be meaningless here.
  const fieldLines = a.fields.map(f => {
    const child = ownedCollectionChild(a, f);
    return fieldLine(f, child ? `${child.name}[]` : tsType(f.type));
  });
  // one member per machine region, typed as the union of its state-name literals (as render/types.ts)
  const regionMembers = (a.machine?.regions ?? []).map(r =>
    `  ${r.name}: ${r.states.map(s => `'${s.name}'`).join(' | ')};`);
  const own = `export interface ${a.name} {\n${[...fieldLines, ...regionMembers].join('\n')}\n}\n`;
  const children = (a.entities ?? []).map(entityIface);
  return [own, ...children].join('\n');
}

export function renderTsTypes(model: DomainModel): string {
  const out: string[] = [`// GENERATED by lattice from context ${model.context} — DO NOT EDIT. Regenerate instead.`, ''];

  if (model.builtins?.length) {
    out.push('// Opaque `builtin` carriers — external types; supply a real type by editing/importing if wanted.');
    for (const b of model.builtins) out.push(`export type ${b.name} = unknown;${b.ref ? `   // external: ${b.ref}` : ''}`);
    out.push('');
  }

  // Plain enums → string-literal unions. Sum-type enums (any variant carries a payload) → a
  // discriminated union tagged by `kind`, payload under `value` (TS has no positional ADT variant).
  for (const e of model.enums) {
    if (e.payloads && Object.keys(e.payloads).length) {
      const arms = e.values.map(v => e.payloads![v] ? `{ kind: '${v}'; value: ${tsType(e.payloads![v]!)} }` : `{ kind: '${v}' }`);
      out.push(`export type ${e.name} = ${arms.join(' | ')};`);
    } else {
      out.push(`export type ${e.name} = ${e.values.map(v => `'${v}'`).join(' | ')};`);
    }
  }
  if (model.enums.length) out.push('');

  // `type` records → interfaces. Aliases are NOT emitted: they're inlined at use sites (CML
  // semantics), so every reference already carries the resolved type.
  const blocks = [
    ...(model.records ?? []).map(r => iface(r.name, r.fields)),
    ...model.values.map(valueIface),
    ...model.entities.map(entityIface),
    ...model.aggregates.map(aggregateIface),
    ...model.events.map(eventIface),
  ];
  out.push(blocks.join('\n'));
  return out.join('\n').replace(/\n+$/, '\n');
}
