import { describe, it, expect } from 'vitest';
import { renderTsTypes } from './ts-types.js';
import { loadLatText } from '../../parse/fromLangium.js';
import type { DomainModel } from '../../ast/domain.js';

// Slice 3: the faithful full-model TS emitter. Fixture is built through the real parser (loadLatText)
// so head-Optional normalization (→ `?`), carrier resolution, and union flattening are all exercised
// exactly as production input arrives. Assertions are on rendered strings (the output is a faithful
// type SURFACE — it references external generic/carrier types and is not run through tsc).

const SPEC = `context Rich {
  builtin Metadata
  builtin Currency
  enum Mode { fast, slow }
  value Amount {
    amount   : Money
    currency : Currency
  }
  entity DraftWithBill { draftId : Id key }
  entity DraftWithInvoice { draftId : Id key }
  aggregate Ledger {
    ledgerId : Id key
    owner    : ref DraftWithBill const
    meta     : Metadata
    mode     : Mode
    approved : Optional<Money>
    balances : Map<Id, Amount>
    settle   : Result<Amount, Metadata>
    holds    : Map<Id, Optional<Money>>
    lifecycle access {
      states { trialing @initial, active @active, ended @terminal }
      transition go { from trialing to active }
    }
  }
  event kicked { reason : Text }
}
`;

function render(spec: string): string {
  const r = loadLatText(spec);
  if (!r.ok) throw new Error(`load failed: ${JSON.stringify(r.diagnostics)}`);
  return renderTsTypes(r.model);
}

describe('renderTsTypes — faithful per-kind output', () => {
  const ts = render(SPEC);

  it('emits a header naming the context', () => {
    expect(ts).toContain('// GENERATED by lattice from context Rich — DO NOT EDIT. Regenerate instead.');
  });

  it('emits an alias block for declared builtin carriers', () => {
    expect(ts).toContain('export type Metadata = unknown;');
    expect(ts).toContain('export type Currency = unknown;');
  });

  it('emits enums as string-literal unions', () => {
    expect(ts).toContain("export type Mode = 'fast' | 'slow';");
  });

  it('emits a value interface with prim (Money→number) and carrier sub-fields', () => {
    expect(ts).toContain('export interface Amount {\n  amount: number;\n  currency: Currency;\n}');
  });

  it('renders a key/const field as readonly, Id→string', () => {
    expect(ts).toContain('  ledgerId: string;');
    expect(ts).toContain('  readonly owner: string;');   // ref → foreign id string; const → readonly
  });

  it('renders a carrier field by its bare name and an enum field by its alias', () => {
    expect(ts).toContain('  meta: Metadata;');
    expect(ts).toContain('  mode: Mode;');
  });

  it('renders a head Optional<Money> as an optional property (not `| null`)', () => {
    expect(ts).toContain('  approved?: number;');
    expect(ts).not.toContain('approved: number | null');
  });

  it('renders Map<K,V> as Record and a nested Optional as `| null`', () => {
    expect(ts).toContain('  balances: Record<string, Amount>;');
    expect(ts).toContain('  holds: Record<string, number | null>;');
  });

  it('renders a generic ctor faithfully with resolved args', () => {
    expect(ts).toContain('  settle: Result<Amount, Metadata>;');
  });

  it('renders a machine region as a state-literal union member', () => {
    expect(ts).toContain("  access: 'trialing' | 'active' | 'ended';");
  });

  it('emits an event interface', () => {
    expect(ts).toContain('export interface kicked {\n  reason: string;\n}');
  });
});

describe('renderTsTypes — unions, nested children, exhaustiveness, determinism', () => {
  it('renders a union of arms joined by `|`', () => {
    const ts = render(`context C {
  builtin A builtin B
  aggregate G { gId : Id key  pick : A | B }
}`);
    expect(ts).toContain('  pick: A | B;');
  });

  it('emits a nested aggregate-owned child as its own interface', () => {
    const ts = render(`context C {
  aggregate Invoice {
    invoiceId : Id key
    lines     : List<InvoiceLine>
    entity InvoiceLine { lineId : Id key  amount : Money }
  }
}`);
    expect(ts).toContain('export interface InvoiceLine {\n  lineId: string;\n  amount: number;\n}');
    expect(ts).toContain('  lines: InvoiceLine[];');   // owned collection → T[]
  });

  it('distinguishes an owned collection (embed child) from a foreign ref list (id strings)', () => {
    // `plans: List<ref Plan>` where Plan is TOP-LEVEL is NOT an owned collection — its elements are
    // foreign ids, so it renders `string[]`, unlike the owned `lines: InvoiceLine[]` above.
    const ts = render(`context C {
  entity Plan { planId : Id key }
  aggregate Cart {
    cartId : Id key
    plans  : List<ref Plan>
  }
}`);
    expect(ts).toContain('  plans: string[];');
    expect(ts).not.toContain('plans: Plan[]');
  });

  it('never throws on any TypeRef kind (all ten present)', () => {
    // prim, enum, ref, value, list, optional, map, generic, union, carrier
    const ts = render(`context All {
  builtin Blob
  enum E { a, b }
  value V { n : Money }
  entity Ent { entId : Id key }
  aggregate Agg {
    aggId : Id key
    p     : Int
    e     : E
    r     : ref Ent
    v     : V
    l     : List<Int>
    o     : Optional<Money>
    m     : Map<Id, Int>
    g     : Wrapper<Int>
    u     : E | V
    c     : Blob
  }
}`);
    expect(ts).toContain('export interface Agg {');
    expect(ts).toContain('  g: Wrapper<number>;');
    expect(ts).toContain('  o?: number;');
    expect(ts).toContain('  c: Blob;');
  });

  it('is deterministic (pure)', () => {
    const r = loadLatText(SPEC);
    expect(r.ok).toBe(true);
    if (!r.ok) return;
    const a = renderTsTypes(r.model);
    const clone = JSON.parse(JSON.stringify(r.model)) as DomainModel;
    expect(renderTsTypes(clone)).toBe(a);
  });
});
