import type { GenPlan, PlanAggregate } from '../plan.js';
import type { Field, TypeRef } from '../../ast/domain.js';

function tsType(t: TypeRef): string {
  switch (t.kind) {
    case 'prim': return t.prim === 'Text' || t.prim === 'Id' ? 'string' : 'number'; // Int/Money/Date/Duration → number (ticks)
    case 'enum': return 'string';
    case 'ref': return 'string';           // foreign id
    case 'list': return `${tsType(t.of)}[]`;
    case 'value': return t.value;
  }
}

function fieldLine(f: Field): string { return `  ${f.name}: ${tsType(f.type)};`; }

function aggregateInterface(a: PlanAggregate): string {
  const lines = a.fields.map(fieldLine);
  for (const r of a.regions) {
    const union = r.states.map(s => `'${s.name}'`).join(' | ');
    lines.push(`  ${r.name}: ${union};`);
  }
  return `// spec: aggregate ${a.name}\nexport interface ${a.name} {\n${lines.join('\n')}\n}\n`;
}

export function renderTypes(plan: GenPlan): string {
  const header = `// GENERATED by lattice from context ${plan.context} — DO NOT EDIT. Regenerate instead.\n\n`;
  const aggs = plan.aggregates.map(aggregateInterface).join('\n');
  const events = plan.events.map(e =>
    `// spec: event ${e.name}\nexport interface ${e.name} {\n${e.fields.map(fieldLine).join('\n')}\n}\n`).join('\n');
  return header + aggs + '\n' + events;
}
