// GENERATED by lattice conform --contract from context Subscriptions — DO NOT EDIT.
// Regenerating the spec regenerates this file; stale overrides then FAIL TO COMPILE (design §4.2).

export interface SubscriptionSpecState {
  subId: string;
  plan: string | null;
  seats: number;
  periodStart: number;
  periodEnd: number;
  accruedUnits: number;
  paidInvoiceCount: number;
  maxRetries: number;
  latestInvoice: string | null;
  status: 'trialing' | 'active' | 'pastDue' | 'canceled' | 'expired';
}
export interface InvoiceSpecState {
  invoiceId: string;
  subscription: string | null;
  licenseFeeAmount: number;
  usageAmount: number;
  totalDue: number;
  amountPaid: number;
  retryCount: number;
  settlement: 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';
}

export interface SpecOverrides {
  Subscription?: { [K in keyof SubscriptionSpecState]?: (db: unknown, row: Record<string, unknown>) => SubscriptionSpecState[K] };
  Invoice?: { [K in keyof InvoiceSpecState]?: (db: unknown, row: Record<string, unknown>) => InvoiceSpecState[K] };
}

export function defineOverrides(o: SpecOverrides): SpecOverrides { return o }

export interface DriveGen { int(min: number, max: number): number; id(): string; pick<T>(xs: T[]): T; clock(): number }
export type DriveOutcome = { accepted: true } | { accepted: false; rejected: string };
export interface SpecDrivers {
  transitions: {
    activate(db: unknown, row: SubscriptionSpecState, gen: DriveGen): void;
    expireTrial(db: unknown, row: SubscriptionSpecState, gen: DriveGen): void;
    paymentFailed(db: unknown, row: SubscriptionSpecState, gen: DriveGen): void;
    recover(db: unknown, row: SubscriptionSpecState, gen: DriveGen): void;
    cancel(db: unknown, row: SubscriptionSpecState, gen: DriveGen): void;
    dunningExhausted(db: unknown, row: SubscriptionSpecState, gen: DriveGen): void;
    finalize(db: unknown, row: InvoiceSpecState, gen: DriveGen): void;
    settle(db: unknown, row: InvoiceSpecState, gen: DriveGen): void;
    voidDraft(db: unknown, row: InvoiceSpecState, gen: DriveGen): void;
    voidOpen(db: unknown, row: InvoiceSpecState, gen: DriveGen): void;
    writeOff(db: unknown, row: InvoiceSpecState, gen: DriveGen): void;
  };
  superset?: Record<string, (db: unknown, row: SubscriptionSpecState | InvoiceSpecState, gen: DriveGen) => void>;
  create: {
    Subscription?(db: unknown, id: string, gen: DriveGen): void;
    Invoice?(db: unknown, id: string, gen: DriveGen): void;
  };
}

export function defineDrivers(d: SpecDrivers): SpecDrivers { return d }
