// GENERATED by lattice conform --contract from context Subscriptions — DO NOT EDIT.
// Regenerating the spec regenerates this file; stale overrides then FAIL TO COMPILE (design §4.2).

export interface SubscriptionSpecState {
  subId: string;
  plan: string;
  seats: number;
  periodStart: number;
  periodEnd: number;
  accruedUnits: number;
  paidInvoiceCount: number;
  maxRetries: number;
  latestInvoice: string;
  status: 'trialing' | 'active' | 'pastDue' | 'canceled' | 'expired';
}
export interface InvoiceSpecState {
  invoiceId: string;
  subscription: string;
  licenseFeeAmount: number;
  usageAmount: number;
  totalDue: number;
  amountPaid: number;
  retryCount: number;
  settlement: 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';
}

export interface SpecOverrides {
  Subscription?: { [K in keyof SubscriptionSpecState]?: (db: unknown, row: Record<string, unknown>) => SubscriptionSpecState[K] };
  Invoice?: { [K in keyof InvoiceSpecState]?: (db: unknown, row: Record<string, unknown>) => InvoiceSpecState[K] };
}

export function defineOverrides(o: SpecOverrides): SpecOverrides { return o }
